# Generated by Django 3.0.4 on 2020-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('imgTop', models.CharField(max_length=200)),
                ('imgRight', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('visibleImgLeft', models.BooleanField(default=True)),
            ],
        ),
    ]
