# Generated by Django 3.0.4 on 2020-03-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='visibleImgLeft',
            new_name='visibleImgRight',
        ),
    ]
