# Generated by Django 3.0.4 on 2020-03-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pages_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
