# Generated by Django 3.0.4 on 2020-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200323_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content_en',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_th',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_th',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
