# Generated by Django 3.0.4 on 2020-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('info_supp', models.CharField(max_length=500)),
                ('date_expedition', models.CharField(max_length=30)),
                ('transport_mode', models.CharField(max_length=20)),
                ('livraison', models.CharField(max_length=255)),
                ('livraison_country', models.CharField(max_length=30)),
                ('dimension', models.CharField(max_length=255)),
                ('type_emballage', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
                ('volume_unite', models.CharField(max_length=10)),
                ('poids', models.CharField(max_length=30)),
                ('poids_unite', models.CharField(max_length=10)),
                ('marchandise', models.CharField(max_length=255)),
                ('lieu_enlevement', models.CharField(max_length=255)),
                ('enlevement_country', models.CharField(max_length=50)),
            ],
        ),
    ]
